### ISSUE TITLE
Hello, is this an Ubuntu touch for op3?

### ISSUE THREAD

**Issue by hu19960925** [Halium/android_device_oneplus_oneplus3#4]
Hello, is this an Ubuntu touch for op3?

**Comment by idontknow420** [comment]
No, its not. But it is important step to get halium first if we need ubuntu or any other os.

**Comment by Vince1171** [comment]
Now there is UT on Oneplus3/3T :D
you can install it with the [installer](github.com/ubports/ubports-installer)

**Comment by idontknow420** [comment]
I just checked but there is no armhf in installer why ? or is that not
needed ?

**Comment by Vince1171** [comment]
armhf should come soon I hope.
armhf is not needed but arm64 there are still some missing feature on arm64... It doesn't include the openstore for example
