### ISSUE TITLE
build/core/product_config.mk:268: *** No matches for product "lineage_oneplus3".  Stop.

### ISSUE THREAD

**Issue by linsmod** [Halium/android_device_oneplus_oneplus3#8]
<pre><font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ source build/envsetup.sh 
including device/oneplus/oneplus3/vendorsetup.sh
including vendor/cm/vendorsetup.sh
including sdk/bash_completion/adb.bash
including vendor/cm/bash_completion/git.bash
including vendor/cm/bash_completion/repo.bash
<font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ breakfast oneplus3 
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:268: *** No matches for product &quot;lineage_oneplus3&quot;.  Stop.
build/core/product_config.mk:268: *** No matches for product &quot;cm_oneplus3&quot;.  Stop.
build/core/product_config.mk:268: *** No matches for product &quot;lineage_oneplus3&quot;.  Stop.
Device oneplus3 not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_oneplus3
Traceback (most recent call last):
  File &quot;vendor/cm/build/tools/roomservice.py&quot;, line 263, in &lt;module&gt;
    default_revision = get_default_revision()
  File &quot;vendor/cm/build/tools/roomservice.py&quot;, line 117, in get_default_revision
    return r.replace(&apos;refs/heads/&apos;, &apos;&apos;).replace(&apos;refs/tags/&apos;, &apos;&apos;)
AttributeError: &apos;NoneType&apos; object has no attribute &apos;replace&apos;
build/core/product_config.mk:268: *** No matches for product &quot;lineage_oneplus3&quot;.  Stop.
build/core/product_config.mk:268: *** No matches for product &quot;lineage_oneplus3&quot;.  Stop.

** Don&apos;t have a product spec for: &apos;lineage_oneplus3&apos;
** Do you have the right repo manifest?</pre>

**Comment by linsmod** [comment]
according to https://docs.halium.org/ and use haliium-7.1, any help?

**Comment by ernesst** [comment]
Did you follow that page : http://docs.halium.org/en/latest/porting/get-sources.html ?

**Comment by linsmod** [comment]
yes, the device xml file already exists, I do sync and breakfast, but it fails when breakfast.

**Comment by ernesst** [comment]
Try this : https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild

**Comment by linsmod** [comment]
> Try this : https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild

it works!

however the build failed as some errors, i tried again and output this:

<pre><font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ mka halium-boot systemimage hybris-boot
make: Entering directory &apos;/home/tiny/halium&apos;
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
LINEAGE_VERSION=14.1-20191231-UNOFFICIAL-oneplus3
TARGET_PRODUCT=halium_oneplus3
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.0.0-37-generic-x86_64-with-Zorin-15-bionic
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NOF27B
OUT_DIR=/home/tiny/halium/out
============================================
Running kati to generate build-halium_oneplus3.ninja...
No need to regenerate ninja file
Starting build with ninja
ninja: Entering directory `.&apos;
[  0% 5/22924] Lex: libsepol_32 &lt;= external/selinux/libsepol/cil/src/cil_lexer.l
FAILED: /bin/bash -c &quot;prebuilts/misc/linux-x86/flex/flex-2.5.39 -o/home/tiny/halium/out/host/linux-x86/obj32/SHARED_LIBRARIES/libsepol_intermediates/cil/src/cil_lexer.c external/selinux/libsepol/cil/src/cil_lexer.l&quot;
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt &lt; (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))&apos; failed.
Aborted
[  0% 5/22924] Building Kernel Config
make: Entering directory &apos;/home/tiny/halium/kernel/oneplus/msm8996&apos;
make[1]: Entering directory &apos;/home/tiny/halium/out/target/product/oneplus3/obj/KERNEL_OBJ&apos;
  GEN     ./Makefile
drivers/soc/qcom/Kconfig:368:warning: choice value used outside its choice group
drivers/soc/qcom/Kconfig:373:warning: choice value used outside its choice group
#
# configuration written to .config
#
make[1]: Leaving directory &apos;/home/tiny/halium/out/target/product/oneplus3/obj/KERNEL_OBJ&apos;
make: Leaving directory &apos;/home/tiny/halium/kernel/oneplus/msm8996&apos;
make: Entering directory &apos;/home/tiny/halium/kernel/oneplus/msm8996&apos;
make[1]: Entering directory &apos;/home/tiny/halium/out/target/product/oneplus3/obj/KERNEL_OBJ&apos;
  GEN     ./Makefile
scripts/kconfig/conf --savedefconfig=defconfig Kconfig
drivers/soc/qcom/Kconfig:368:warning: choice value used outside its choice group
drivers/soc/qcom/Kconfig:373:warning: choice value used outside its choice group
make[1]: Leaving directory &apos;/home/tiny/halium/out/target/product/oneplus3/obj/KERNEL_OBJ&apos;
make: Leaving directory &apos;/home/tiny/halium/kernel/oneplus/msm8996&apos;
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target &apos;ninja_wrapper&apos; failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory &apos;/home/tiny/halium&apos;

<font color="#AA0000">#### make failed to build some targets (4 seconds) ####</font>

<font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ 
</pre>

**Comment by linsmod** [comment]
Ok, it build success after i add a locale setting to .bashrc
`export LC_ALL=C `

**Comment by ernesst** [comment]
@kissstudio you should join the group UBports Porting telegram.

**Comment by linsmod** [comment]
> @kissstudio you should join the group UBports Porting telegram.

I'm in now. :P

**Comment by linsmod** [comment]
> Ok, it build success after i add a locale setting to .bashrc
> `export LC_ALL=C `

i found the Halium doc gives a solution about this error
https://docs.halium.org/en/latest/porting/common-system-build-errors.html#flex-locale-error
